language: php

php:
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script:
  - ./bin/phpspec run --format=pretty
  - ./bin/phpunit --testdox
