language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - 7.0

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - bin
    - vendor
    - bower_components
    - $HOME/.composer/cache

install:
  - ./setup.sh

script:
# Disable phpspec run for now
#  - ./bin/phpspec run --format=pretty
  - ./bin/phpunit --testdox
